server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_lab
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

app:
  queues:
    subscription-created: subscription-created